apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.deploymentName }}
  labels:
    app: nginx
spec:
  replicas: {{ .values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: {{ .values.containers.name }}
        image: {{ .values.image.repository }}:{{ .values.containers.tag }}
        ports:
        - containerPort: {{ .values.containers.containerPort }}
